# Generated by Django 2.2.24 on 2021-10-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_auto_20211024_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='interests_description',
            field=models.TextField(default='Something about me..'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='messenger_alias',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='picture_url',
            field=models.URLField(default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png', max_length=120),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='telegram_alias',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
