# Generated by Django 2.2.24 on 2021-10-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_auto_20211028_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
